# golangci-lint v1.x config (for CI compatibility)
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/TheBranchDriftCatalyst/cli-tools

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
