version: 3

includes:
  go: ./taskfiles/Taskfile.go.yaml
  test: ./taskfiles/Taskfile.test.yaml
  shell: ./taskfiles/Taskfile.shell.yaml
  clean: ./taskfiles/Taskfile.clean.yaml
  dev: ./taskfiles/Taskfile.dev.yaml
  ci: ./taskfiles/Taskfile.ci.yaml

vars:
  CMD_DIR:
    sh: realpath ./cmd
  SCRIPTS_DIR:
    sh: realpath ./scripts
  LOCAL_BIN:
    sh: realpath ./bin

tasks:

  default:
    desc: Show help information
    silent: true
    cmds:
      - task: dev:help

  build:
    desc: Build all CLI commands (Go + shell scripts)
    silent: false
    cmds:
      - task: shell:build
      - task: go:build
      - task: permissions

  permissions:
    desc: Set permissions for the binary files
    sources: [ "{{ .LOCAL_BIN }}/*", "{{ .SCRIPTS_DIR }}/*" ]
    cmds:
      - for: sources
        cmd: chmod +x {{ .ITEM }}

  install:
    deps: [ build, permissions ]
    desc: Install CLI tools to PATH via zshrc
    cmds:
      - ./install.sh

  uninstall:
    desc: Remove CLI tools from PATH
    cmds:
      - ./uninstall.sh

  deploy:
    deps: [ build, permissions ]
    desc: "[DEPRECATED] Use 'task install' instead. Legacy symlink deployment."
    sources:
      - "{{ .LOCAL_BIN }}/*"
    generates:
      - "{{ .REAL_BIN }}/*"
    cmds:
      - for: sources
        cmd: ln -sf $(realpath {{ .ITEM }}) {{ .REAL_BIN }}/{{ base .ITEM}}

  # Convenience aliases for common tasks
  fmt:
    desc: Format Go code
    cmds:
      - task: go:fmt

  vet:
    desc: Run go vet on Go code
    cmds:
      - task: go:vet

  lint:
    desc: Run all linters
    cmds:
      - task: test:lint

  help:
    desc: Show help message
    cmds:
      - task: dev:help
