version: 3

vars:
  CMD_SRC:
    sh: realpath ./cmd
  DEPLOY_BIN:
    sh: realpath ~/bin
  CLI_BIN:
    sh: realpath ./bin

tasks:

  # default:
  #   desc: Run the build and deploy tasks
  #   cmds:
  #   - echo {{ .DEPLOY_BIN }}
  #   - task --list-all
  deploy:path-shim:
    desc: Deploy the path shim
    cmds:
    - ln -sf {{ .CLI_BIN }}/{{ base .ITEM }} {{ .DEPLOY_BIN }}/{{ base .ITEM }}

  build:
    desc: Build the CLI commands
    silent: false
    cmds:
    # - task: build:go
    - task: shell:build
    - task: go:build
    - task: permissions
    # - task: deploy-bin

  shell:build:
    silent: false
    desc: Build the shell scripts
    sources:
    - "./shell/*"
    # generates:
    # - "{{ .DEPLOY_BIN }}/*"
    cmds:
    - for: sources
      # cmd: echo {{ .DEPLOY_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }}
      cmd: cp {{ .ITEM }} {{ .DEPLOY_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }}

  go:build:
    desc: Build the CLI commands
    silent: false
    sources:
    - "{{ .CMD_SRC }}/**/main.go"
    # generates:
    # - "{{ .DEPLOY_BIN }}/*"
    cmds:
    - for: sources
      # cmd: echo {{ .DEPLOY_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }}
      cmd: go build -o {{ .DEPLOY_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }} {{ .ITEM }}
    - task: permissions

  # deploy-bin:
  #   desc: Deploy the binary files
  #   sources:
  #   - "{{ .CLI_BIN }}/*"
  #   cmds:
  #   - for: sources
  #     cmd: ln -sf {{ .ITEM }} {{ .DEPLOY_BIN }}/{{ base .ITEM }}

  permissions:
    desc: Set permissions for the binary files
    sources: [ "{{ .CLI_BIN }}/*", "./scripts/*" ]
    cmds:
    - for: sources
      cmd: chmod +x {{ .ITEM }}

  build:package:
    desc: Build the package
    cmds:
    - echo "Building package..."
    - task: "./scripts/*"
