version: 3

vars:
  CMD_SRC:
    sh: realpath ./cmd
  REAL_BIN:
    # NOTE that this is out of repo scope!!!! for now
    sh: realpath ~/bin
  LOCAL_BIN:
    sh: realpath ./bin

tasks:

  default:
    desc: Run the build and deploy tasks
    silent: true
    cmds:
    # TODO: make this default display sexier, with task names as well
    - "echo \"REAL_BIN: {{ .REAL_BIN }}\""
    - "echo \"LOCAL_BIN: {{ .LOCAL_BIN }}\""

  clean:caches:
    desc: Clean the caches
    cmds:
    - rm -rf .task

  build:
    desc: Build the CLI commands
    silent: false
    cmds:
    # - task: build:go
    - task: shell:build
    - task: go:build
    - task: permissions
    # - task: deploy-bin

  shell:build:
    silent: false
    desc: Build the shell scripts
    sources:
    - "./shell/*"
    # generates:
    # - "{{ .DEPLOY_BIN }}/*"
    cmds:
    - for: sources
      # cmd: echo {{ .DEPLOY_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }}
      cmd: cp {{ .ITEM }} {{ .DEPLOY_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }}

  go:build:
    desc: Build the CLI commands
    silent: false
    sources:
    - "{{ .CMD_SRC }}/**/main.go"
    generates:
    - "{{ .LOCAL_BIN }}/*"
    cmds:
    - for: sources
      # cmd: echo {{ .LOCAL_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }}
      cmd: go build -o {{ .LOCAL_BIN }}/{{ trimPrefix "cmd/" (dir .ITEM) }} {{ .ITEM }}
    - task: permissions

  organize:
    desc: Move shell scripts from bin/ to shell/ directory
    cmds:
    - |
      for script in bin/*.sh bin/*.py; do
        [ -f "$script" ] && mv "$script" shell/ && echo "Moved $(basename $script) to shell/"
      done

  install:
    deps: [ build, permissions ]
    desc: Install CLI tools to PATH via zshrc
    cmds:
    - ./install.sh

  uninstall:
    desc: Remove CLI tools from PATH
    cmds:
    - ./uninstall.sh

  deploy:
    deps: [ build, permissions ]
    desc: "[DEPRECATED] Use 'task install' instead. Legacy symlink deployment."
    sources:
    - "{{ .LOCAL_BIN }}/*"
    generates:
    - "{{ .REAL_BIN }}/*"
    cmds:
    - for: sources
      cmd: ln -sf $(realpath {{ .ITEM }}) {{ .REAL_BIN }}/{{ base .ITEM}}

  permissions:
    desc: Set permissions for the binary files
    sources: [ "{{ .LOCAL_BIN }}/*", "shell/*" ]
    cmds:
    - for: sources
      cmd: chmod +x {{ .ITEM }}
